spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testing
    username: test
    password: test
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 9080
